[package]
name = "liveletters-friend"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
clap = { workspace = true, features = ["derive"] }
liveletters-app-core = { path = "../liveletters-app-core" }
liveletters-output = { path = "../liveletters-output" }
liveletters-store = { path = "../liveletters-store" }
liveletters-utils = { path = "../liveletters-utils" }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
