[package]
name = "liveletters-mail"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[features]
default = []
network = ["dep:native-tls"]

[dependencies]
liveletters-mime = { path = "../liveletters-mime" }
liveletters-protocol = { path = "../liveletters-protocol" }
liveletters-log = { path = "../liveletters-log" }
liveletters-utils = { path = "../liveletters-utils" }
native-tls = { workspace = true, optional = true }
